# specify the node base image with your desired version node:<version>
FROM node:10
# replace this with your application's default port
EXPOSE 3000

#Specify the node base image with your desired version node:<version>
FROM node:10
ENV NODE_ENV=production
# replace this with your application's default port
EXPOSE 3000
COPY covid-watson-assistant /home/node/app/
RUN chown -R node /home/node/app
WORKDIR /home/node/app
USER node
CMD npm start
